# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          user: firassziedan
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.activity+community, isocalendar, base.repositories, languages, topics
          config_timezone: Asia/Amman
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_habits: no
          #plugin_habits_days: 14
          #plugin_habits_facts: yes
          #plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: smali
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_mode: "mastered"
          plugin_wakatime: no
